### ISSUE TITLE
Any example how to use this crate with nom?

### ISSUE THREAD

**Issue by bbigras** [jeremydavis519/runtime-macros#3]
I'm a bit confused by the current example code. Do I need proc_macro to test a [nom](https://crates.io/crates/nom) macro or is proc_macro only needed to declare the macro being tested in the example?

**Comment by jeremydavis519** [comment]
Yeah, I can see how it's confusing. Hopefully this clears it up. I'd be happy to make changes to the example or documentation that you think will help.

The example code really does three things: (1) declare the procedural macro `custom_assert`, (2) test that macro with the tests found in [custom_assert/tests](https://github.com/jeremydavis519/runtime-macros/tree/master/examples/custom_assert/tests), and (3) run additional code coverage tests, which are found in [lib.rs](https://github.com/jeremydavis519/runtime-macros/blob/master/examples/custom_assert/src/lib.rs), in the `tests` module at the bottom. That third part is the only reason the example depends on runtime-macros, so it's what the example should be focused on. I'm not sure that's clear enough now that I look at it again.

To answer what I think you're asking, you technically only need `#[proc_macro]` for part (1), declaring the procedural macro. That attribute tells rustc that it should be treated as a macro instead of a function (which allows part (2) to work as expected). The core of part (3), the code coverage tests, is this line:
```rust
        emulate_macro_expansion_fallible(file, "custom_assert", custom_assert_internal).unwrap();
```
At least when I wrote this example (and I don't think it's changed since then), rustc wouldn't allow me to use the function that I'd declared with `#[proc_macro]` as a regular function, so I couldn't use `custom_assert` as the third argument here. So I made that function a stub and put all the logic into `custom_assert_internal`. You'll have to use the same workaround if you want to use runtime-macros.

In fact, I suppose you could do the code coverage test without actually making anything that rustc would recognize as a macro (i.e. without defining any function with `#[proc_macro]`). I have no idea what the use case would be, though. It wouldn't actually tell you about the code coverage of the other tests.

I haven't actually used nom (the closest I've come is [syn](https://crates.io/crates/syn)), but everything I've said should apply to any procedural macro you could write, regardless of what other crates it uses.

I hope this explanation answered your question well enough. And please let me know if anything else is unclear. I'll be happy to help.

**Comment by bbigras** [comment]
Thank you for your reply.

Not being familiar with proc_macro I'm confusing by custom_assert_internal vs custom_assert. Maybe you can see what I need to do with an example.

Here the `named!` macro will generate my parse_word function that I can use to parse text. The function will parse string beginning with "prefix " and having either "aaa" or "bbb" after.

```rust
use nom::types::CompleteStr;
use nom::{alt, do_parse, error_position, named, tag};

named!(pub parse_word<CompleteStr, CompleteStr>, do_parse!(
    tag!("prefix ") >>
    word: alt!(tag!("aaa") | tag!("bbb")) >>
        (word)
));

#[cfg(test)]
fn nom_result<R, T>((_, v): (R, T)) -> T {
    v
}

#[test]
fn test_parse() {
    assert_eq!(
        parse_word(CompleteStr("prefix aaa"))
            .map(nom_result)
            .unwrap(),
        CompleteStr("aaa")
    );

    assert_eq!(
        parse_word(CompleteStr("prefix bbb"))
            .map(nom_result)
            .unwrap(),
        CompleteStr("bbb")
    );

    assert!(parse_word(CompleteStr("prefix ccc")).is_err());
}
```

**Comment by jeremydavis519** [comment]
Okay, I think I understand the confusion now. You've made a parser that looks like it'll work, and it's called using the `parse_word` at runtime. I think that'll be the case with most nom parsers. Unless you're making your _own_ macro, you don't need runtime-macros. If you want code coverage tests, you can just use a code coverage tool like [tarpaulin](https://crates.io/crates/cargo-tarpaulin) directly, since everything's already happening at runtime. The only thing runtime-macros does is cause some code that would normally run at compile-time to happen at runtime so that one of those tools can report how much of it is being tested.

If you are looking to make a new macro, I'd recommend using syn instead of nom. Basically, you'll want to make a macro if the stuff you're parsing belongs in your source code file, and you'll want to make a runtime parser (like the one in your example) if you want to parse things at runtime from a separate file or user input.

**Comment by bbigras** [comment]
In my example, if I remove the second `asser_eq!()` (the one testing "bbb") , tarpaulin will still report a 100% code coverage. Maybe it's a limitation of tarpaulin (they still have some other kind of coverage on their roadmap).

I was hoping that maybe expanding the macro would make it so that all my case are on different lines are that the code coverage would be accurate.

I thought that maye I could just use `--pretty=expanded` and feed it back to rustc like [the old book](https://doc.rust-lang.org/1.5.0/book/macros.html) said but the code didn't compile.

I'll take a look at syn. Thanks.
